# Generated by Django 5.2.17 on 2026-08-26 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampoPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="nombre del campo"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TEXTO", "Texto"),
                            ("NUMERO", "Número"),
                            ("FECHA", "Fecha"),
                        ],
                        default="TEXTO",
                        max_length=10,
                        verbose_name="tipo de dato",
                    ),
                ),
            ],
            options={
                "verbose_name": "campo personalizado (armamento)",
                "verbose_name_plural": "campos personalizados (armamento)",
            },
        ),
        migrations.CreateModel(
            name="Compania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
            ],
            options={
                "verbose_name": "compañía",
                "verbose_name_plural": "compañías",
            },
        ),
        migrations.CreateModel(
            name="Deposito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
            ],
            options={
                "verbose_name": "depósito",
                "verbose_name_plural": "depósitos",
            },
        ),
        migrations.CreateModel(
            name="TipoArmamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="tipo de armamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de armamento",
                "verbose_name_plural": "tipos de armamento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "unidad",
                "verbose_name_plural": "unidades",
            },
        ),
        migrations.CreateModel(
            name="Armamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="número de serie"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        choices=[("DEPOSITO", "En depósito"), ("EN_MANO", "En mano")],
                        default="DEPOSITO",
                        max_length=10,
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("BAJA", "Dado de baja")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "motivo_baja",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DANO", "Dañado"),
                            ("PERDIDA", "Perdido"),
                            ("ROBO", "Robado"),
                        ],
                        max_length=10,
                        verbose_name="motivo de baja",
                    ),
                ),
                (
                    "fecha_baja",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de baja"
                    ),
                ),
                (
                    "datos_extra",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos adicionales"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="armamentos",
                        to="inventory.compania",
                    ),
                ),
                (
                    "deposito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="armamentos",
                        to="inventory.deposito",
                    ),
                ),
            ],
            options={
                "verbose_name": "armamento",
                "verbose_name_plural": "armamento",
                "ordering": ["numero_serie"],
            },
        ),
        migrations.CreateModel(
            name="Soldado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apellidos_nombres",
                    models.CharField(
                        max_length=200, verbose_name="apellidos y nombres"
                    ),
                ),
                (
                    "compania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soldados",
                        to="inventory.compania",
                    ),
                ),
            ],
            options={
                "verbose_name": "soldado",
                "verbose_name_plural": "soldados",
                "ordering": ["apellidos_nombres"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTREGA", "Entrega (a soldado)"),
                            ("DEVOLUCION", "Devolución (a depósito)"),
                        ],
                        max_length=12,
                        verbose_name="tipo de movimiento",
                    ),
                ),
                (
                    "observacion",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observación"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha y hora"
                    ),
                ),
                (
                    "armamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventory.armamento",
                    ),
                ),
                (
                    "deposito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventory.deposito",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soldado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventory.soldado",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento",
                "verbose_name_plural": "movimientos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="armamento",
            name="soldado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="armamentos",
                to="inventory.soldado",
            ),
        ),
        migrations.AddField(
            model_name="armamento",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="armamentos",
                to="inventory.tipoarmamento",
            ),
        ),
        migrations.AddField(
            model_name="compania",
            name="unidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companias",
                to="inventory.unidad",
            ),
        ),
        migrations.AddIndex(
            model_name="armamento",
            index=models.Index(
                fields=["numero_serie"], name="inventory_a_numero__b68b42_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="compania",
            constraint=models.UniqueConstraint(
                fields=("unidad", "nombre"), name="uq_compania_unidad_nombre"
            ),
        ),
    ]
