# Generated by Django 5.2.17 on 2026-08-29 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoarmamento',
            name='control',
            field=models.CharField(choices=[('SERIE', 'Por serie individual'), ('CANTIDAD', 'Por cantidad')], default='SERIE', max_length=10, verbose_name='forma de control'),
        ),
        migrations.CreateModel(
            name='Peloton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pelotones', to='inventory.compania')),
            ],
            options={
                'verbose_name': 'pelotón',
                'verbose_name_plural': 'pelotones',
                'ordering': ['compania__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='soldado',
            name='peloton',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='soldados', to='inventory.peloton'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=80, verbose_name='número de lote')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('compania_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_recibidos', to='inventory.compania')),
                ('compania_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_realizados', to='inventory.compania')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventory.deposito')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='inventory.tipoarmamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=80, verbose_name='número de lote')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventory.compania')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventory.deposito')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventory.tipoarmamento')),
            ],
            options={
                'verbose_name': 'existencia',
                'verbose_name_plural': 'existencias',
                'ordering': ['tipo__nombre', 'compania__nombre'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'compania', 'deposito', 'lote'), name='uq_existencia_tipo_compania_deposito_lote')],
            },
        ),
        migrations.AddConstraint(
            model_name='peloton',
            constraint=models.UniqueConstraint(fields=('compania', 'nombre'), name='uq_peloton_compania_nombre'),
        ),
    ]
