# Generated by Django 5.2.17 on 2026-08-30 01:12

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_tipoarmamento_control_peloton_soldado_peloton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armamento',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, encoder=apps.inventory.models.UnicodeJSONEncoder, verbose_name='datos adicionales'),
        ),
    ]
