# Generated by Django 5.2.17 on 2026-08-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_armamento_datos_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTREGA', 'Entrega (a soldado)'), ('DEVOLUCION', 'Devolución (a depósito)'), ('BAJA', 'Baja')], max_length=12, verbose_name='tipo de movimiento'),
        ),
    ]
