# Generated by Django 5.2.17 on 2026-10-01 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_movimiento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoExistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega (a soldado)'), ('DEVOLUCION', 'Devolución (a depósito)')], max_length=12, verbose_name='tipo de movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('existencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventory.existencia')),
                ('soldado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_existencia', to='inventory.soldado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_existencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de existencia',
                'verbose_name_plural': 'movimientos de existencia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ExistenciaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('existencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventory.existencia')),
                ('soldado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias_asignadas', to='inventory.soldado')),
            ],
            options={
                'verbose_name': 'existencia asignada',
                'verbose_name_plural': 'existencias asignadas',
                'ordering': ['existencia__tipo__nombre', 'soldado__apellidos_nombres'],
                'constraints': [models.UniqueConstraint(fields=('existencia', 'soldado'), name='uq_existencia_asignada_existencia_soldado')],
            },
        ),
    ]
