# Generated by Django 5.2.17 on 2026-10-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_movimientoexistencia_existenciaasignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldado',
            name='grado',
            field=models.CharField(blank=True, choices=[('TC', 'TC'), ('MY', 'MY'), ('CT', 'CT'), ('TE', 'TE'), ('ST', 'ST'), ('SM', 'SM'), ('SP', 'SP'), ('SV', 'SV'), ('SS', 'SS'), ('CP', 'CP'), ('CS', 'CS'), ('C3', 'C3'), ('SLP', 'SLP'), ('SL18', 'SL18')], max_length=10, verbose_name='grado'),
        ),
    ]
